// export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS = 'FETCH_ITEMS';
// export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';

export const FETCH_FAVOURITE_ITEMS_REQUEST = 'FETCH_FAVOURITE_ITEMS_REQUEST';
export const FETCH_FAVOURITE_ITEMS_SUCCESS = 'FETCH_FAVOURITE_ITEMS_SUCCESS';
export const FETCH_FAVOURITE_ITEMS_FAILURE = 'FETCH_FAVOURITE_ITEMS_FAILURE';

// export const UPDATE_ITEM_REQUEST = 'UPDATE_ITEM_REQUEST';
export const UPDATE_ITEM = 'UPDATE_ITEM';
// export const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE';
