export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE';

export const FETCH_FAVOURITE_ITEMS_SUCCESS = 'FETCH_FAVOURITE_ITEMS_SUCCESS';
export const FETCH_FAVOURITE_ITEMS_FAILURE = 'FETCH_FAVOURITE_ITEMS_FAILURE';

export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const UPDATE_ITEM_FAILURE = 'UPDATE_ITEM_FAILURE';
