export const FETCH_SUBMISSONS_SUCCESS = 'FETCH_SUBMISSONS_SUCCESS';
export const FETCH_SUBMISSONS_FAILURE = 'FETCH_SUBMISSONS_FAILURE';
export const FETCH_SUBMISSONS_REQUEST = 'FETCH_SUBMISSONS_FAILURE';

export const FETCH_USER_SUBMISSONS_SUCCESS = 'FETCH_USER_SUBMISSONS_SUCCESS';
export const FETCH_USER_SUBMISSONS_FAILURE = 'FETCH_USER_SUBMISSONS_FAILURE';
export const FETCH_USER_SUBMISSONS_REQUEST = 'FETCH_USER_SUBMISSONS_FAILURE';

export const CREATE_SUBMISSON_SUCCESS = 'CREATE_SUBMISSON_SUCCESS';
export const CREATE_SUBMISSON_FAILURE = 'CREATE_SUBMISSON_FAILURE';
export const CREATE_SUBMISSON_REQUEST = 'CREATE_SUBMISSON_REQUEST';
